config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :carriers

  resources :carrier do
    resources :line_items
  end

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  resources :carts do
    member do
      post :pay
    end
  end
  resources :line_items do
    member do
      put :update_quantity
      get :update_quantity
    end
  end
  root 'carriers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/carrier.rb
class Carrier < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  has_many :line_items
  mount_uploader :image, ImageUploader
  serialize :image, JSON # If you use SQLITE, add this line
  belongs_to :user, optional: true

  validates :surname, :lastname, :price, presence: true
  validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed." }
  validates :price, length: { maximum: 7 }

  private

  def not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end
end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController
  before_action :set_carrier, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /carriers
  # GET /carriers.json
  def index
    @carriers = Carrier.all.order("created_at desc")
  end

  # GET /carriers/1
  # GET /carriers/1.json
  def show
  end

  # GET /carriers/new
  def new
    @carrier = current_user.carriers.build
  end

  # GET /carriers/1/edit
  def edit
  end

  # POST /carriers
  # POST /carriers.json
  def create
    @carrier = current_user.carriers.build(carrier_params)

    respond_to do |format|
      if @carrier.save
        format.html { redirect_to @carrier, notice: 'Carrier was successfully created.' }
        format.json { render :show, status: :created, location: @carrier }
      else
        format.html { render :new }
        format.json { render json: @carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carriers/1
  # PATCH/PUT /carriers/1.json
  def update
    respond_to do |format|
      if @carrier.update(carrier_params)
        format.html { redirect_to @carrier, notice: 'Carrier was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrier }
      else
        format.html { render :edit }
        format.json { render json: @carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carriers/1
  # DELETE /carriers/1.json
  def destroy
    @carrier.destroy
    respond_to do |format|
      format.html { redirect_to carriers_url, notice: 'Carrier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrier
      @carrier = Carrier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrier_params
      params.require(:carrier).permit(:surname, :lastname, :description, :price, :image)
    end
end

app/helpers/carriers_helper.rb
module CarriersHelper

  def carrier_author(carrier)
    user_signed_in? && current_user.id == carrier.user_id
  end
end

app/views/carriers/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @carrier, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :surname , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column">
            <div class="control">
              <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        </div>

        <div class="field">
          <div class="control">
            <%= f.input :lastname, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.input :description, placeholder: "Who are you? Which means of transport do you use? Which district do you prefer?", required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <label class="label">Add images</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input carrier-image" }, label: false, wrapper: false %>
                  <span class="file-cta button is-warning">
                    <span class="file-icon"><i class="fa fa-upload button is-warning"></i></span>
                    <span class="file-label button is-warning">Choose a file…</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, class: 'button is-warning' %>
            <%= link_to 'Cancel', carriers_path, class:'button is-danger is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/carriers/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" style="color:white;">
        Editing Carrier
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', carrier: @carrier %>
</div>

app/views/carriers/index.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" style="color:white;">
        Browse the latest transporter on iTransport
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="instrument-index-grid pt4">
  <% @carriers.each do |carrier| %>

    <div class="instrument border-light">
      <div class="instrument-thumb">
      <%= link_to image_tag(carrier.image_url(:thumb)), carrier %>

      <% if carrier.surname? %>
        <div class="surname">
          <span class="tag is-dark"><%= carrier.surname %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to carrier.surname, carrier %></h3>

      <p class="has-text-gray fg pt1">Sold by <%= carrier.user.name %></p>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(carrier.price) %></p>

      <% if carrier_author(carrier) %>
         <%= link_to 'Edit', edit_carrier_path(carrier), class: "button is-warning is-small" %>
         <%= link_to 'Delete', carrier, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-danger is-small" %>
      <% end %>

    </div>
  </div>
  <% end %>
</div>

app/views/carriers/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title" style="color:white;">
        Sell your service as a Carrier
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', carrier: @carrier %>
</div>

app/views/carriers/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section instrument-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @carrier.surname %></h1>

      <ul class="pv1">
        <% if @carrier.lastname? %>
        <li class="inline-block pr3"><%= @carrier.lastname %></li>
        <% end %>

      <div class="feature-image">
        <%= image_tag(@carrier.image_url(:default)) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Description</h3>
      <%= @carrier.description %>

    </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@carrier.price) %></h4>
        <p class="has-text-centered mb4">Sold by <%= @carrier.user.name %></p>
        <%= button_to 'Add to cart', line_items_path(carrier_id: @carrier), class: 'button is-warning add-to-cart' %>
      </div>
    </div>
  </div>

  <% if carrier_author(@carrier) %>
    <%= link_to 'Edit', edit_carrier_path(@carrier), class: 'button is-warning' %>
  <% end %>
</section>