config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :carriers

  resources :carrier do
    resources :line_items
  end

  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  resources :carts do
    member do
      post :pay
    end
  end
  resources :line_items do
    member do
      put :update_quantity
      get :update_quantity
    end
  end
  root 'carriers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iTransport</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <style media="screen">
/*
      .footer {
        height:70px;
        margin-top: 150px;
        background-color: black;
        text-align: center;
        color: white;
        }
        */
    </style>
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-warning" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5">iTransport</h1>
        <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">

          <% if total_cart_items %>
              <%= link_to cart_path(@cart), class:"navbar-item button is-warning" do %>
             <span class="icon is-small">
                <i class="fa fa-shopping-cart"></i>
              </span>
              <span>Cart
                <%= cart_count_over_one %>
                </span>
              <% end %>
            <% end %>

            <% if user_signed_in? %>
              <%= link_to 'Sell your Service', new_carrier_path, class: "navbar-item button is-dark" %>

              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>
            <% else %>

            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-warning" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-warning"%>

            <% end %>

            </div>
          </div>
        </div>
    </div>
  </nav>

  <%= yield(:header) %>

  <div class="container">

    <%= yield %>

  </div>
  </body>
<!--
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
        <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
        is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
      </p>
    </div>
  </footer>
  -->
  <!--
  <footer>
    <div class="footer">
      <%= link_to root_path, class:"" do %>
        <h1 style="color:white;" align="center">@iTransport</h1>
      <% end  %>
      All rights reserved 2019.</div>
      <div>
        <p style="background-color: #ffdd57;">
          <br>
        </p>
      </div>
  </footer>
-->
</html>